export const keyboardLayout = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace"
  ],
  ["Tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\"],
  ["Caps", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "Enter"],
  ["", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "Shift"]
]

export const keyColors = {
  q: "bg-purple-200",
  w: "bg-green-200",
  e: "bg-pink-200",
  r: "bg-cyan-200",
  t: "bg-cyan-200",
  y: "bg-yellow-200",
  u: "bg-yellow-200",
  i: "bg-pink-200",
  o: "bg-orange-200",
  p: "bg-green-200",
  a: "bg-purple-200",
  s: "bg-green-200",
  d: "bg-pink-200",
  f: "bg-cyan-200",
  g: "bg-cyan-200",
  h: "bg-yellow-200",
  j: "bg-yellow-200",
  k: "bg-pink-200",
  l: "bg-orange-200",
  z: "bg-purple-200",
  x: "bg-green-200",
  c: "bg-pink-200",
  v: "bg-cyan-200",
  b: "bg-cyan-200",
  n: "bg-yellow-200",
  m: "bg-yellow-200"
}
